@baseUrl = http://localhost:4004/myService

### GET All Subjects
GET {{baseUrl}}/subject

### GET All Students
GET {{baseUrl}}/student

###
GET {{baseUrl}}/staff

### GET All Staff
GET {{baseUrl}}/getStaff(role='3',subjectsTaught_ID='2')

### GET All Admin
GET {{baseUrl}}/adminLogon


### 
POST {{baseUrl}}/staffLogon
Content-Type: application/json

{
    "ID"        : "1",
    "email"     : "ankit@merckgroup.com",
    "password"  : "123456" 
}
###------------------------###

### GET Subjects by specific ID
GET {{baseUrl}}/subject(5)

### Dynamic Subquery
GET {{baseUrl}}/getSubject(ID='',subName='Sociology')

### Dynamic Subquery
GET {{baseUrl}}/verifyStaffLogon
Content-Type: application/json

{

    "email": "ankit@merckgroup.com",
    "password": "123456"
}

###
# POST {{baseUrl}}/postSubject(ID='5',name='Biology',description='Biology Book',classLevel='8')

###
POST {{baseUrl}}/postManySubject
Content-Type: application/json

{
"values": 
   [{
        "ID": "12",
        "name": "Finology",
        "description": "Finology Book",
        "classLevel": "7"
    },{
        "ID": "13",
        "name": "Advance Java",
        "description": "Advance Java Book",
        "classLevel": "8"
    }] 
}

###
PUT {{baseUrl}}/subject(1)
Content-Type: application/json

{
      "classLevel": 8,
      "description": "Sociology Book",
      "name": "Sociology",
      "subjectTeacher_ID": 2
}
###
PUT {{baseUrl}}/subject(4)
Content-Type: application/json

{
      "classLevel": 8,
      "description": "History Book",
      "name": "History",
      "subjectTeacher_ID": 2
}
